# Generated by Django 3.2.6 on 2021-08-12 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210812_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='date_last_saved',
            field=models.DateTimeField(default='2021-08-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='header',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
