# Generated by Django 3.2.6 on 2021-08-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='date_last_saved',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
